#!/usr/bin/env python3
"""
Report Agent — Boxer3D v3.0
Takes biomechanics analysis data and generates:
  - Clinical summary
  - Patient-friendly report
  - Exercise recommendations
  - Follow-up recommendations

Part of the multi-agent MSK assessment pipeline.
"""
import sys
import json
from pathlib import Path
from datetime import datetime


def generate_clinical_summary(biomechanics_data: dict, patient_info: dict = None) -> dict:
    """Generate structured clinical report from biomechanics analysis."""
    
    if "error" in biomechanics_data:
        return {"error": biomechanics_data["error"]}
    
    summary = biomechanics_data.get("summary", {})
    risk = biomechanics_data.get("risk_assessment", {})
    angles = biomechanics_data.get("average_angles", {})
    rom = biomechanics_data.get("range_of_motion", {})
    
    # Build findings
    findings = []
    
    # Range of motion findings
    for joint, data in rom.items():
        if data.get("status") == "limited":
            findings.append({
                "type": "ROM_deficit",
                "joint": joint.replace("_", " ").title(),
                "measured": data["measured"],
                "norm": f"{data['norm'][0]}-{data['norm'][1]}°",
                "severity": "moderate" if data["measured"] < data["norm"][0] * 0.7 else "mild"
            })
    
    # Asymmetry findings
    sym_score = summary.get("symmetry_score", 100)
    if sym_score < 80:
        findings.append({
            "type": "movement_asymmetry",
            "score": sym_score,
            "severity": "significant" if sym_score < 60 else "moderate",
            "note": "Asymmetrical movement pattern detected"
        })
    
    # Risk-based findings
    for finding in risk.get("findings", []):
        findings.append({
            "type": "risk_indicator",
            "detail": finding,
            "severity": "high"
        })
    
    # Generate exercise recommendations
    exercises = []
    if any(f["type"] == "ROM_deficit" for f in findings):
        deficit_joints = [f["joint"] for f in findings if f["type"] == "ROM_deficit"]
        for j in deficit_joints:
            exercises.append({
                "target": j,
                "type": "stretching",
                "frequency": "daily",
                "duration": "15-30 seconds, 3 reps",
                "note": f"Gentle {j.lower()} stretching to improve range of motion"
            })
    
    if sym_score < 80:
        exercises.append({
            "target": "Core/Balance",
            "type": "stabilization",
            "frequency": "daily",
            "duration": "10 minutes",
            "note": "Unilateral stance and core stability exercises to address asymmetry"
        })
    
    # Clinical impression
    risk_level = risk.get("level", "unknown")
    impressions = {
        "low": "Patient demonstrates normal movement patterns with no significant biomechanical deficits.",
        "moderate": "Patient shows mild to moderate biomechanical deviations that may benefit from targeted intervention.",
        "high": "Patient exhibits significant biomechanical dysfunction requiring clinical attention."
    }
    
    report = {
        "report_type": "MSK Biomechanical Assessment",
        "generated": datetime.now().isoformat(),
        "patient": patient_info or {"id": "unknown", "name": "Patient"},
        "clinical_impression": impressions.get(risk_level, ""),
        "risk_summary": {
            "level": risk_level,
            "score": risk.get("score", 0),
            "interpretation": "Needs intervention" if risk_level == "high" else "Monitor" if risk_level == "moderate" else "Within normal limits"
        },
        "findings": findings,
        "key_metrics": {
            "symmetry_score": sym_score,
            "frames_analyzed": biomechanics_data.get("frames_analyzed", 0),
            "significant_findings": len(findings)
        },
        "exercise_plan": exercises,
        "recommendations": [
            "Follow up in 2 weeks for reassessment",
            "Perform prescribed exercises daily",
            "Report any increase in pain or discomfort",
            "Consider referral to physical therapy if no improvement in 4 weeks"
        ],
        "disclaimer": "This analysis is generated by AI and should be reviewed by a licensed healthcare professional."
    }
    
    return report


def generate_patient_summary(report: dict) -> str:
    """Convert clinical report to patient-friendly language."""
    risk = report["risk_summary"]
    findings = report.get("findings", [])
    
    lines = []
    lines.append("═" * 50)
    lines.append("  BOXER3D MOVEMENT ASSESSMENT — PATIENT SUMMARY")
    lines.append("═" * 50)
    lines.append("")
    lines.append(f"Date: {report['generated'][:10]}")
    lines.append(f"Patient: {report['patient'].get('name', 'Patient')}")
    lines.append("")
    
    if findings:
        lines.append("📋 WHAT WE FOUND:")
        for f in findings:
            icon = "🔴" if f.get("severity") == "high" else "🟡"
            lines.append(f"  {icon} {f.get('detail', f.get('note', ''))}")
        lines.append("")
    
    lines.append(f"📊 OVERALL: {risk['level'].upper()} risk ({risk['score']}/100)")
    lines.append("")
    
    if report.get("exercise_plan"):
        lines.append("🏋️ RECOMMENDED EXERCISES:")
        for ex in report["exercise_plan"]:
            lines.append(f"  • {ex['target']}: {ex['note']}")
        lines.append("")
    
    lines.append("💡 NEXT STEPS:")
    for rec in report.get("recommendations", []):
        lines.append(f"  • {rec}")
    
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Boxer3D Report Agent")
    parser.add_argument("biomechanics_json", help="Biomechanics agent output JSON")
    parser.add_argument("--output", "-o", help="Output path")
    parser.add_argument("--patient", "-p", default="Patient", help="Patient name")
    args = parser.parse_args()
    
    with open(args.biomechanics_json) as f:
        biomech_data = json.load(f)
    
    report = generate_clinical_summary(biomech_data, {"name": args.patient})
    output_path = args.output or Path(args.biomechanics_json).parent / "report_output.json"
    with open(output_path, "w") as f:
        json.dump(report, f, indent=2)
    
    print(generate_patient_summary(report))
    
    summary_path = Path(output_path).parent / "patient_summary.txt"
    with open(summary_path, "w") as f:
        f.write(generate_patient_summary(report))
    print(f"\nFull reports saved to {output_path} and {summary_path}")
